music/urls.py
from django.conf.urls import url
from . import views 
from django.conf import settings

app_name = 'music'

urlpatterns = [
	#/music/
	url(r'^$', views.index_view, name = 'index'),

	url(r'^logout/$', views.logout, name='logout'),

	url(r'^login/$', views.auth, name='authenticate'),

	url(r'^signup/$', views.UserFormView.as_view(), name='signup'),

	url(r'^search', views.search, name="search"),
	#/music/<album_id>/
	url(r'^album/(?P<pk>[0-9]+)/$', views.detail_view, name = 'detail'),

	url(r'^users/$', views.all_users, name = 'all_users'),

	url(r'^album/(?P<pk>[0-9]+)/favorite/$', views.favorite_album, name = 'favorite_album'),

	url(r'^favorited-albums/$', views.favorited_albums, name = 'favorite_albums'),
	#/music/album/add
	url(r'album/add/$', views.album_create, name='album-add'),

	#music/album/2
	url(r'album/(?P<pk>[0-9]+)/update/$', views.album_update, name='album-update'),

	#music/album/2/delete
	url(r'album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
	#music/album/2/add-song
	url(r'album/(?P<pk>[0-9]+)/add-song/$', views.album_song_create, name='album-add-song'),

	#music/album/2/song/favorite
	url(r'^songs/(?P<pk>[0-9]+)/favorite/$', views.favorite_song, name='favorite_song'),

	url(r'^songs/(?P<pk>[0-9]+)/favorite-song/$', views.favorite_song_in_songs, name='favorite_in_songs'),
	#music/songs
	url(r'^songs/$', views.songs_view, name='songs'),

	url(r'^song/(?P<pk>[0-9]+)/$', views.song_view, name ='song_view'),

	url(r'songs/favorite-songs/$', views.favorited_songs, name='favorite_songs'),

	#music/album/2/song/delete_song/2/
	url(r'^song/add/$', views.song_create, name='song-add'),

	url(r'^song/(?P<pk>[0-9]+)/update/$', views.song_update, name='song-update'),

	url(r'^song/(?P<pk>[0-9]+)/delete/$', views.delete_song, name='song-delete'),

	url(r'^songs/song/(?P<pk>[0-9]+)/delete-song/$', views.delete_song_in_songs, name='song-delete-in-songs'),
	
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static 
from music import views as music_views


urlpatterns = [
   	url(r'^$', music_views.index_view, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^music/', include('music.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
from music.choices import GENRE_CHOICES

@python_2_unicode_compatible
class Artist(models.Model):
	name = models.CharField(max_length=200)
	source_id = models.CharField(max_length=200)

	def compare(self, value):
		compare = float(len(value))/len(self.name)
		return compare

	def __str__(self):
		return self.name

@python_2_unicode_compatible
class Album(models.Model):
	album_title = models.CharField(max_length=250)
	album_logo = models.FileField()
	creator = models.ForeignKey(User, null = True, related_name = "album_creator")
	users = models.ManyToManyField(User)

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk' : self.pk})

	def __str__(self):
		return self.album_title

		
@python_2_unicode_compatible
class Song(models.Model):
	album = models.ForeignKey(Album, on_delete = models.CASCADE, null = True)
	song_title = models.CharField(max_length=200)
	creator = models.ForeignKey(User, related_name = "creator")
	artist = models.ForeignKey(Artist)
	users = models.ManyToManyField(User)
	genre = models.IntegerField(choices=GENRE_CHOICES)
	tempo = models.IntegerField()

	def compare(self, value):
		compare = float(len(value))/len(self.song_title)
		return compare

	def get_tempo_display(self):
		if self.tempo < 90:
			return 'Slow'
		elif self.tempo <= 120:
			return 'Medium'
		else:
			return 'Fast'

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk' : self.album.pk})

	def __str__(self):
		return self.song_title

class Profile(models.Model):
	user = models.OneToOneField(User, on_delete = models.CASCADE)

	def get_initials(self):
		if self.user.first_name and self.user.last_name:
			first_letter = self.user.first_name[0]
			second_letter = self.user.last_name[0]	
			initials = first_letter + second_letter
			return initials
		else:
			first_letter = self.user.username[0]
			second_letter = self.user.username[1]
			initials = first_letter + second_letter
			return initials

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

class Comment(models.Model):
	author = models.ForeignKey(User)
	song = models.ForeignKey(Song)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)

music/forms.py
from django.contrib.auth.models import User
from django import forms
from models import Album, Song, Comment
from django.contrib.auth.forms import UserCreationForm


class SignUp_UserForm(forms.ModelForm):
	first_name = forms.CharField(max_length=30, help_text='Enter your firsts name')
	last_name = forms.CharField(max_length=30, help_text='Enter your last name')
	password = forms.CharField(widget = forms.PasswordInput)
	class Meta:
		model = User
		fields= ['username', 'first_name', 'last_name', 'email','password']


class Registration_UserForm(forms.ModelForm):
	password = forms.CharField(widget = forms.PasswordInput)
	class Meta:
		model = User
		fields = ['username', 'email', 'password', 'first_name', 'last_name']

class AlbumForm(forms.ModelForm):
	class Meta:
		model = Album
		fields = ['album_title','album_logo']
	def __init__(self, *args, **kwargs):
		creator = kwargs.pop('creator')
		super(AlbumForm, self).__init__(*args, **kwargs)
		self.instance.creator = creator

class SongForm(forms.ModelForm):
	class Meta:
		model = Song
		fields = ['album', 'song_title', 'genre','artist', 'tempo']

	def __init__(self, *args, **kwargs):
		creator=kwargs.pop('creator')
		super(SongForm, self).__init__(*args, **kwargs)
		self.instance.creator = creator

class AlbumSongForm(forms.ModelForm):
	class Meta:
		model = Song
		fields = ['song_title', 'genre', 'artist', 'tempo']

	def __init__(self, *args, **kwargs):
		album = kwargs.pop('album')
		creator=kwargs.pop('creator')
		super(AlbumSongForm, self).__init__(*args, **kwargs)
		self.instance.album = album
		self.instance.creator = creator

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('text',)

    def __init__(self, *args, **kwargs):
    	author = kwargs.pop('author')
    	super(CommentForm, self).__init__(*args, **kwargs)
    	self.instance.author = author

music/views.py
from django.views import generic 
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.decorators.csrf import csrf_protect
from django.core.urlresolvers import reverse_lazy, reverse
from django.shortcuts import render, redirect, get_object_or_404, render_to_response
from django.contrib import messages, auth
from django.contrib.auth import authenticate, logout as auth_logout, login as auth_login, get_user_model
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from music.models import Album, Song, Artist
from music.forms import Registration_UserForm, AlbumSongForm, AlbumForm, SongForm,SignUp_UserForm, CommentForm
from music.choices import GENRE_CHOICES
from django import forms
from django.http import QueryDict, HttpResponseRedirect
from django.db.models import Count, Q, CharField, Case, Value, When, F, BooleanField
from copy import copy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from itertools import chain
import operator

@login_required
def index_view(request):
    albums = Album.objects.all()
    context_object_name = 'all_albums'
    user_favorite_albums = request.user.album_set.all()

    for album in albums:
         album.is_favorite = album in user_favorite_albums

    return render(request,'music/index.html', {
        'albums':albums,
        })

def detail_view(request, pk):
    album = get_object_or_404(Album, pk= pk)
    songs = album.song_set.all()
    user_favorite_songs = request.user.song_set.all()
    for song in songs:
        song.is_favorite = song in user_favorite_songs
    return render(request,'music/detail.html', {'album':album, 'songs':songs})   

def song_view(request, pk):
    song = get_object_or_404(Song, pk=pk)
    user = request.user
        
    initials = user.profile.get_initials()
    if request.method == "POST":
        form = CommentForm(request.POST, author = user)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.song = song
            comment.save()
            return redirect('music:song_view', pk=pk)
    else:
        form = CommentForm(author = user)
    
    comments = song.comment_set.all().order_by('-created_date')
    return render(request,'music/song.html', {
        'song':song, 
        'initials': initials, 
        'form':form,
        'comments': comments 
    }) 

@login_required
def songs_view(request):
    all_songs = Song.objects.all()

    filters_map = {
        'tempo': {
            'slow': {'tempo__lt': 90},
            'medium': {'tempo__range': (90, 120)},
            'fast': {'tempo__gt': 120},
        },
        'genre': {
            'rock': {'genre': 1},
            'hiphop': {'genre': 2},
            'pop': {'genre': 3},
            'metal': {'genre': 4},
            'jazz': {'genre': 5},
        }
    }

    genre_dict = dict(GENRE_CHOICES)

    genre_title_map = {
        'rock': genre_dict[1],
        'hiphop': genre_dict[2],
        'pop': genre_dict[3],
        'metal': genre_dict[4],
        'jazz': genre_dict[5],
    }

    def apply_filters(qs, filters):
        for k,v in filters.iteritems():
            qs = qs.filter(**filters_map[k][v])
        return qs

    from collections import OrderedDict

    order_fields = OrderedDict([
        ('artist__name', {
            '': ('artist__name', ''),
            'artist__name': ('-artist__name', 'up'),
            '-artist__name': ('', 'down'),
        }),
        ('song_title', {
            '': ('song_title', ''),
            'song_title': ('-song_title', 'up'),
            '-song_title': ('', 'down'),
            }),
        ('tempo', {
            '': ('tempo', ''),
            'tempo': ('-tempo', 'up'),
            '-tempo': ('', 'down'),
            }),
        ('genre', {
            '': ('genre', ''),
            'genre': ('-genre', 'up'),
            '-genre': ('', 'down'),
            }),
    ])

    order = request.GET.get('order', 'id')
    orders = []
    for o_field in order_fields.keys():
        if order in order_fields[o_field]:
            order_field, order_direction = order_fields[o_field][order]
            orders.append({
                    'order': order_direction,
                    'order_title': o_field.replace('_', ' ').title(),
                    'order_field': order_field
                })
        else:
            orders.append({
                    'order': '',
                    'order_title': o_field.replace('_', ' ').title(),
                    'order_field': o_field
                })


    def apply_order(qs, order):
        if order:
            return qs.order_by(order)
        return qs.order_by('id')

    filter_names = {'tempo', 'genre'}
##  
    def get_filters(get):
        return {k:v for k,v in get.iteritems() if v and k in filter_names}

    filters = get_filters(request.GET)
    songs = apply_filters(all_songs, filters)

    songs = apply_order(songs, order)

    filters_wo_genre = copy(filters)
    filters_wo_genre.pop('genre', None)
    genre_filters = apply_filters(all_songs, filters_wo_genre).annotate(
        genre_title = Case(
            When((Q(genre = 1)), then=Value('rock')),
            When((Q(genre = 2)), then=Value('hiphop')),
            When((Q(genre = 3)), then=Value('pop')),
            When((Q(genre = 4)), then=Value('metal')),
            When((Q(genre = 5)), then=Value('jazz')),
            output_field = CharField()
        )).values('genre_title').annotate(cnt=Count('pk')).values('genre_title', 'cnt').order_by('cnt')
    for f in genre_filters:
        f['title'] = genre_title_map[f['genre_title']]

    filters_wo_tempo = copy(filters)
    filters_wo_tempo.pop('tempo', None)
    tempo_filters = apply_filters(all_songs, filters_wo_tempo).annotate(
        tempo_speed=Case(
            When((Q(tempo__lt = 90)), then=Value('slow')),
            When((Q(tempo__range=(90, 120))), then=Value('medium')),
            When((Q(tempo__gt = 120)), then=Value('fast')),
            output_field = CharField()
        )).values('tempo_speed').annotate(cnt=Count('pk')).values('tempo_speed', 'cnt').order_by('cnt')
    for f in tempo_filters:
        f['title'] = f['tempo_speed'].title()

    paginator = Paginator(songs, 15)
    page = request.GET.get('page')

    try:
        song_paginator = paginator.page(page)
    except PageNotAnInteger:
        song_paginator = paginator.page(1)
    except EmptyPage:
        song_paginator = paginator.page(paginator.num_pages)

    filters_get = QueryDict(mutable=True)
    filters_get.update(request.GET.dict())

    if request.GET.get('order') == order:
        filters_get.pop('order')

    return render(request,'music/songs.html', {
        'song_paginator':song_paginator,
        'genres' : genre_filters ,
        'tempos' : tempo_filters ,
        'orders' : orders,
        'artists': Artist.objects.all(),
        'filters_get': filters_get,
   }) 
    
def album_create(request):
    user = request.user
    template_name = 'music/index.html'
    if request.method == 'POST':
        form = AlbumForm(request.POST, request.FILES, creator=user)
        if form.is_valid():
            album = form.save()
            return redirect('music:index')
    else:
        form = AlbumForm(creator=user)
    return render(request, 'music/album_form.html', {
        'creator':user,
        'form':form
    }) 


def album_update(request, pk):
    user = request.user
    album =get_object_or_404(Album, pk=pk)
    if user!=album.creator:
        messages.add_message(request, messages.INFO, 'You cannot update this album, because you are not the creator.')
        return redirect('music:index')
    else:
        if request.POST:
            form = AlbumForm(request.POST, request.FILES,instance = album, creator = album.creator)
            if form.is_valid():
                form.save()
                return redirect('music:index')
        form = AlbumForm(instance = album, creator=album.creator)
        return render(request, 'music/album_form.html', {
        'creator':user,
        'form':form
    }) 

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

def song_create(request):
    user = request.user
    template_name = 'music/songs.html'
    if request.method == 'POST':
        form = SongForm(request.POST,creator=user)
        if form.is_valid():
            song = form.save()
            return redirect('music:songs')
    else:
        form = SongForm(creator=user)
    return render(request, 'music/song_form.html', {
        'creator':user,
        'form':form
    }) 

def album_song_create(request, pk):
    album = Album.objects.get(pk=pk)
    user = request.user
    if request.method == 'POST':
        form = AlbumSongForm(request.POST, album=album, creator = user)
        if form.is_valid():
            song = form.save()
            return redirect(album)
    else:
        form = AlbumSongForm(album=album, creator=user)

    return render(request, 'music/song_form.html', {
        'album':album,
        'form':form
    }) 

def song_update(request, pk):
    user = request.user
    song = get_object_or_404(Song, pk=pk)
    if user!=song.creator:
        messages.add_message(request, messages.INFO, 'You cannot update this song, because you are not the creator.')
        return redirect('music:songs')
    else:
        if request.POST:
            form = SongForm(request.POST,instance = song, creator= song.creator)
            if form.is_valid():
                form.save()
                return redirect('music:songs')
        form = SongForm(instance = song, creator=song.creator)
        return render(request, 'music/song_form.html', {
        'creator':user,
        'form':form
    }) 

def delete_song(request, pk):
    song = get_object_or_404(Song, pk = pk)
    album = get_object_or_404(Album, pk = song.album.pk)
    song.delete()

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title>{% block title %}fLor1na{% endblock %}</title>
		{% load staticfiles %}
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"> 
		<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'> 
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script> 
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script> 
		<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}"/>﻿
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
	</head>
	<body>
		{% if messages %}
		<ul class="messages">
		    {% for message in messages %}
		    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
		    {% endfor %}
		</ul>
		{% endif %}

		
		{%if user.is_authenticated%}
		<nav class="navbar navbar-inverse">
			<div class="container-fluid">
		
				<!-- Header -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>	
					</button>
					<a class="navbar-brand" href="{% url 'music:index' %}"> {{user.username}} </a>
				</div>


				<!-- Items -->
				<div class="collapse navbar-collapse" id="#topNavBar">
					<ul class="nav navbar-nav">
						{% if request.get_full_path == "/music/" %}
							<li class=" active ">
						{%else%}
							<li class ="#">
						{%endif%}
							<a href="{% url 'music:index' %}">
								<span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Albums
							</a>
						</li>
						{% if request.get_full_path == "/music/songs/" %}
							<li class="active">
						{%else%}
							<li class="#">
						{%endif%}
							<a href="{% url 'music:songs' %}">
								<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Songs
							</a>
						</li>
					</ul>
					<form class="navbar-form navbar-left" method="get" action="{% url 'music:search' %}">
						<div class="form-group">
							<input type="text" class="form-control" name="q" value="">
						</div>
						<button type="submit" class="btn btn-default">Search</button>
					</form>
					<ul class="nav navbar-nav navbar-right">
						{%if request.get_full_path == "/music/favorited-albums/"%}
						<li class="active">
						{%else%}
						<li class="#">
						{%endif%}
							<a href="{% url 'music:favorite_albums' %}">
								<span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; Favorite Albums
							</a>

						</li>
						{%if request.get_full_path == "/music/album/add/"%}
						<li class="active">
						{%else%}
						<li class="#">
						{%endif%}
							<a href="{% url 'music:album-add' %}">
								<span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
							</a>
						</li>
						<li class="#">
							<a href="{% url 'music:logout' %}">
								<span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
							</a>
						</li>
					</ul>
				</div>

			</div>
		</nav>
		{%else%}
			<nav class="navbar navbar-inverse">
				<div class="container-fluid">
			
					<!-- Header -->
					<div class="navbar-header">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>	
						</button>
					</div>


					<!-- Items -->
					<div class="collapse navbar-collapse" id="#topNavBar">
						<ul class="nav navbar-nav">
							<li>
								<a href="{% url 'music:signup' %}">
								<span aria-hidden="true"></span>&nbsp; Register
								</a>
							</li>
							<li>
								<a href="{% url 'music:authenticate' %}">
								<span aria-hidden="true"></span>&nbsp; Log In
								</a>
							</li>
						</ul>
						</ul>
					</div>
				</div>
			</nav>
			{%endif%}
		{% block body %}

		{% endblock %}
	</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
<!-- {% block albums_active %}active{% endblock %} -->

{% block body %}

<div class="container-fluid songs-container">

    <div class="row">
        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.album_logo %}
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.album_title }}</h1>
                </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:album-update' album.id %}">Edit Album</a></li>
                <li role="presentation" class="active"><a href="{% url 'music:album-add-song' album.id %}">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in songs %}
                            <tr>
                                <td>
                                    <a target="_blank" href="{% url 'music:song_view' song.id %}">
                                    {{ song.song_title }}
                                    </a>
                                </td>
                                <td>
                                    <a target="_blank" href="{{ song.audio_file.url }}">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    {%if song.is_favorite %}
                                        <a href="{% url 'music:favorite_song' song.id %}"  class="btn btn-default btn-sm btn-favorite" role="button">
                                        <span class="glyphicon glyphicon-star favorite" action=""></span></a>
                                    {%else%}
                                         <a href="{% url 'music:favorite_song' song.id %}"  class="btn btn-default btn-sm btn-favorite" role="button">
                                        <span class="glyphicon glyphicon-star" action=""></span></a>
                                    {%endif%}
                                </td>
                                <td>
                                    <form action="{% url 'music:song-delete' song.id%}" method="post" 
                                                                                        style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs" onclick="return confirm('Are you sure you want to delete this?')">
                                            <span class="glyphicon glyphicon-remove" ></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/form-template.html
  {% csrf_token %}

  {{ form.non_field_errors }}

  {% for hidden_field in form.hidden_fields %}
    {{ hidden_field.errors }}
    {{ hidden_field }}
  {% endfor %}

  <table border="1">
    {% for field in form.visible_fields %}
      <tr>
        <th>{{ field.label_tag }}</th>
        <td>
          {{ field.errors }}
          {{ field }}
          {{ field.help_text }}
        </td>
      </tr>
    {% endfor %}
  </table>

music/templates/music/index.html
{% extends 'music/base.html' %}
<!-- {% block albums_active %}active{% endblock %} -->

{% block body %}

<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Albums</h3>
        </div>
        {% if albums %}
            {% for album in albums %}
                <div class="col-sm-8  col-lg-3">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.album_logo.url }}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Favorite Album -->
                            {%if album.is_favorite%}
                            <a href="{% url 'music:favorite_album' album.id%}" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star favorite"></span>
                            </a>
                            {%else%}
                            <a href="{% url 'music:favorite_album' album.id%}" class="btn btn-default btn-sm btn-favorite">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>
                            {%endif%}
                            <!-- Delete Album -->
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm"  onclick="return confirm('Are you sure you want to delete this?')">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                    </div>
                </div>

            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'music:album-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>

    <!-- IF SEARCH - NOT WORKING YET -->
    {% if songs %}
        <div class="row">
            <div class="col-sm-12">
                <h3>Songs</h3>
            </div>
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Song Title</th>
                                    <th>Artist</th>
                                    <th>Audio File</th>
                                    <th>Album</th>
                                    <th>Favorite</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for song in songs %}
                                    <tr>
                                        <td>{{ song.song_title }}</td>
                                        <td>
                                            <a target="_blank" href="{{ song.audio_file.url }}">
                                                <button type="button" class="btn btn-success btn-xs">
                                                    <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                                </button>
                                            </a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:detail' song.album.id %}">
                                                <img src="{{ song.album.album_logo }}" class="img-responsive" style="width: 20px; float: left; margin-right: 10px;" />
                                            </a>
                                            <a href="{% url 'music:detail' song.album.id %}">{{ song.album.album_title }}</a>
                                        </td>
                                        <td>
                                            <a href="{% url 'music:favorite' song.id %}" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

</div>
{% endblock %}